config/routes.rb
Rails.application.routes.draw do
  root "static#home"

  resources :contact_messages, only: [:index, :create, :destroy]
  resources :users
  resources :posts

  controller :sessions do 
    get 'login' => :new
    post 'login' => :create
    get  'logout' => :logout
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/:url" => "static#show"
end

app/views/shared/_contact-form.html.erb
<p id="notice"><p>
<p id="errors"></p>

<section class="resume-section p-3 p-lg-5 d-flex align-items-center bg-primary-gradient" id="contact">
  <div class="w-100">
    <h2>Contact</h2>

    <%= form_with model: @contact_message, url: contact_messages_url(@contact_message), method: "post", class: "contact-form",remote: true do |form| %>
      <%= form.text_field :name, size: 50, placeholder: "FULL NAME"  %> 
      <%= form.text_field :email, size: 50, placeholder: "EMAIL" %> 
      <%= form.text_area :message, cols:49, rows:10, placeholder: "MESSAGE"  %>
      <%= form.submit "Submit", class: "btn btn-primary btn-large" %>
    <% end %>
  </div>
</section>

app/views/shared/_errors.html.erb
<% if flash[:errors] %>
  <ul class="errors p-0">
  <% flash[:errors].each do |error| %>
    <li>
      <%= error %>
    </li>
  <% end %>
  </ul>
<% end %>

app/views/shared/_head-tag.html.erb
  <meta charset="utf-8">

  <% if @post %>
    <meta property="og:title" content="<%= @post.title %>">
    <meta property="og:url" content="<%= request.original_url %>">
    <meta property="og:image" content="<%= polymorphic_url(@post.cover_picture) %>">
    <meta property="og:description" content=" <%= strip_tags( @post.body ) %>">
  <% end %>

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Christopher Apodaca, Local web developer experienced
  in leveraging agile frameworks to provide a robust synopsis for high level overviews. Iterative approaches to corporate strategy foster collaborative thinking to further the overall value proposition.">
  <meta name="author" content="Christopher Apodaca">

  <title>Christopher Apodaca</title>

  <!-- Custom fonts for this template -->
  <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet">

  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-153359664-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-153359664-1');
  </script>

app/views/shared/_header.html.erb
  <nav class="nav-side navbar navbar-expand-lg navbar-dark blog-nav fixed-top" id="sideNav">
    <a class="navbar-brand js-scroll-trigger" href="#page-top">
      <span class="d-block d-lg-none">Christopher Apodaca</span>
      <span class="d-none d-lg-block">
        <%= image_tag "profile-sm.jpg", :class=>"img-fluid img-profile rounded-circle mx-auto mb-2" %>
      </span>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav">
       <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="/">HOME</a>
        </li>
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
        </li>
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="/posts">Blog</a>
        </li>
       
        <% if is_logged? %>
          <li class="nav-item">
            <%= link_to "LOGOUT", {controller: "sessions", action:"logout"}, class: "nav-link js-scroll-trigger" %>
          </li>
        <%end%>

      </ul>
    </div>
  </nav>